<?php

/**
 * seed_test_data.php
 * Script to programmatically generate test data for CyberTasker automated test suites.
 * WARNING: This script will modify the database. It is intended for testing environments.
 */

require_once __DIR__ . '/../api/db.php';
require_once __DIR__ . '/../api/repositories/UserRepository.php';
require_once __DIR__ . '/../api/repositories/TaskRepository.php';
require_once __DIR__ . '/../api/TOTP.php';

$pdo = getDBConnection();
$userRepo = new UserRepository($pdo);
$taskRepo = new TaskRepository($pdo);

echo "Starting Seed Process for CyberTasker Test Suites...\n";
echo "====================================================\n\n";

// Helper: Clear ALL data for a deterministic baseline
echo "Performing hard reset of test environment...\n";
$pdo->exec("DELETE FROM tasks");
$pdo->exec("DELETE FROM user_categories");
$pdo->exec("DELETE FROM user_stats");
$pdo->exec("DELETE FROM auth_logs");
$pdo->exec("DELETE FROM users");

// For SQLite, reset auto-increment counters to ensure ID-based tests are stable
if ($pdo->getAttribute(PDO::ATTR_DRIVER_NAME) === 'sqlite') {
    try {
        $pdo->exec("DELETE FROM sqlite_sequence WHERE name IN ('users', 'tasks', 'user_categories', 'user_stats', 'auth_logs')");
    }
    catch (Exception $e) {
    // Table might not exist yet if fresh, ignore
    }
}
echo "Full database purge complete.\n\n";

// 1. Create Admin_Alpha
echo "1. Generating Admin_Alpha...\n";
$adminId = $userRepo->create('Admin_Alpha', 'admin_alpha@cybertasker.local', password_hash('Pass_Admin_123!!', PASSWORD_DEFAULT), bin2hex(random_bytes(32)));
$pdo->prepare("UPDATE users SET role = 'admin', is_verified = 1 WHERE id = ?")->execute([$adminId]);
echo "   [V] Admin_Alpha created (ID: $adminId)\n";

// Purge baseline default tasks auto-generated by user creation 
$pdo->prepare("DELETE FROM tasks WHERE user_id = ?")->execute([$adminId]);

// 1.1 Inject Security Directives and Admin PDF for Admin_Alpha
$manualSource = __DIR__ . '/../manuals/CyberTasker_Admin_Guide.pdf';
$uploadDir = __DIR__ . '/../api/uploads/';
$pdfAttachment = null;

if (file_exists($manualSource)) {
    if (!is_dir($uploadDir)) {
        mkdir($uploadDir, 0755, true);
    }
    $uniqueName = uniqid('task_file_', true) . '.pdf';
    $destination = $uploadDir . $uniqueName;

    if (copy($manualSource, $destination)) {
        $pdfAttachment = json_encode([[
                "name" => "CyberTasker_Admin_Guide.pdf",
                "path" => "api/uploads/" . $uniqueName,
                "size" => filesize($destination),
                "type" => "application/pdf",
                "uploaded_at" => date('Y-m-d H:i:s')
            ]]);
    }
}

$directives = [
    ['OVERRIDE DEFAULT ACCESS: Update Access Key or initialize new Operative ID and terminate \'admin\' account.', 'Security', 1, 15, 'CRITICAL: The default administrator credentials represent a severe security vulnerability. You must immediately provision a personalized operative account with elevated privileges, or change the default access key to a high-entropy passphrase.'],
    ['PURGE INSTALLER CORE: Terminate \'install.php\' from the server grid immediately.', 'Security', 1, 10, 'Leaving the installation script active on a production grid allows unauthorized entities to re-initialize the database, potentially exposing or destroying all operational data. Delete the file immediately.'],
    ['ACTIVATE NEURAL ENCRYPTION: Navigate to Admin Console and toggle \'STRICT_PASSWORD_POLICY\' to Level 1.', 'Security', 1, 10, 'Activating the strict password policy ensures all new operatives utilize cryptographic-grade access keys, preventing brute-force neural intrusions. Go to the Admin Panel and enforce this setting.'],
    ['SCRUB RESIDUAL TRACES: Remove \'install_test_user.php\' and other leftover test nodes.', 'Security', 2, 5, 'Clean up any leftover testing scripts that were used to validate the system deployment. These unmonitored endpoints are prime vectors for exploitation.'],
    ['CALIBRATE NEURAL LINK: Perform a System Reset to optimize your ocular data stream.', 'System', 3, 5, 'The initial boot sequence may leave fragmented data packets in your visual buffer. A quick system refresh will align your UI components correctly and ensure everything is loaded cleanly into RAM.'],
    ['UPGRADE COFFEE PROTOCOL: Ensure Operative Fuel levels are at maximum stability.', 'System', 3, 5, 'The most critical variable in any system architecture is the biological component. Maintain optimal hydration and caffeine levels to ensure peak performance.']
];

$stmtTask = $pdo->prepare("INSERT INTO tasks (user_id, title, category, priority, points_value, files, description) VALUES (?, ?, ?, ?, ?, ?, ?)");

$first = true;
foreach ($directives as $d) {
    $files = null;
    if ($first && $pdfAttachment) {
        $files = $pdfAttachment;
        $first = false;
    }
    // attachments argument corresponds to the 6th mapped param, which is `files` in db for file uploads
    $stmtTask->execute([$adminId, $d[0], $d[1], $d[2], $d[3], $files, $d[4]]);
}
echo "   [V] Initial Admin security directives deployed.\n\n";

// 2. Create Op_Beta (With TOTP 2FA)
echo "2. Generating Op_Beta (2FA active)...\n";
$betaId = $userRepo->create('Op_Beta', 'op_beta@cybertasker.local', password_hash('Pass_Beta_123!!', PASSWORD_DEFAULT), bin2hex(random_bytes(32)));
$pdo->prepare("UPDATE users SET is_verified = 1 WHERE id = ?")->execute([$betaId]);

// Setup specific TOTP Seed for testing: 'JBSWY3DPEHPK3PXP'
$testSecret = 'JBSWY3DPEHPK3PXP';
$backupCodes = ['AAAA-BBBB', 'CCCC-DDDD', 'EEEE-FFFF', 'GGGG-HHHH', 'IIII-JJJJ'];
$hashedCodes = array_map(function ($c) {
    return password_hash($c, PASSWORD_DEFAULT);
}, $backupCodes);
$userRepo->enableTotp2fa($betaId, $testSecret, json_encode($hashedCodes));
echo "   [V] Op_Beta created (ID: $betaId, 2FA Enabled)\n";

// 2.1 Seed 55 Tasks for Op_Beta to test pagination
echo "   [+] Injecting 55 directives for Op_Beta pagination test...\n";
for ($i = 1; $i <= 55; $i++) {
    $title = "Pagination Test Directive No. " . str_pad($i, 2, '0', STR_PAD_LEFT);
    $priority = ($i % 3) + 1; // Maps to 1, 2, 3
    $status = ($i % 5 === 0) ? 1 : 0; // Every 5th task is completed
    $category = "Work"; // Default category from repo creation
    $points = 10;

    $dueDate = date('Y-m-d H:i:s', strtotime("+" . ($i % 10) . " days"));

    $stmt = $pdo->prepare("INSERT INTO tasks (user_id, title, category, priority, status, points_value, due_date) VALUES (?, ?, ?, ?, ?, ?, ?)");
    $stmt->execute([$betaId, $title, $category, $priority, $status, $points, $dueDate]);
}
echo "   [V] 55 Directives initialized.\n\n";

// 3. Create 100 baseline users for Admin pagination
echo "3. Generating 100 baseline users for Admin Datagrid pagination test...\n";
$insertUserStmt = $pdo->prepare("INSERT INTO users (username, password, email, is_verified, role) VALUES (?, ?, ?, 1, 'user')");
$pdo->beginTransaction();
for ($i = 1; $i <= 200; $i++) {
    $uname = "Test_User_" . str_pad($i, 3, '0', STR_PAD_LEFT);
    $pass = password_hash('Baseline_Pass_1!', PASSWORD_DEFAULT);
    $email = "test.user.$i@cybertasker.local";
    $insertUserStmt->execute([$uname, $pass, $email]);
    $uid = $pdo->lastInsertId();
    // Insert stats row to prevent foreign key errors later
    $pdo->prepare("INSERT INTO user_stats (id, total_points, current_level, badges_json) VALUES (?, 0, 1, '[]')")->execute([$uid]);
}
$pdo->commit();
echo "   [V] 100 baseline test users injected into registry.\n\n";

echo "====================================================\n";
echo "SEED COMPLETE. System ready for automated test suites.\n";

?>